import { IndianRupee } from "lucide-react";

const AllProducts = ({ isMobile }) => {
  const productsList = [
    {
      productName: "Maize Seeds",
      price: "200",
      discount: "142",
      img: "/img/organicsoil.png",
    },
    {
      productName: "Soybean Seeds",
      img: "/img/humitek.png",
      price: "340",
      discount: "230",
    },
    {
      productName: "Cotton Seeds",
      img: "/img/vegitableseeds.png",
      price: "400",
      discount: "370",
    },
    {
      productName: "Groundnut Seeds",
      img: "/img/soilbooster.png",
      price: "158",
      discount: "110",
    },
    {
      productName: "Wheat Seeds",
      img: "/img/organicsoil.png",
      price: "824",
      discount: "567",
    },
    {
      productName: "Rice Seeds",
      img: "/img/humitek.png",
      price: "550",
      discount: "330",
    },
    {
      productName: "Mustard Seeds",
      img: "/img/vegitableseeds.png",
      price: "80",
      discount: "60",
    },
    {
      productName: "Sunflower Seeds",
      img: "/img/soilbooster.png",
      price: "170",
      discount: "150",
    },
  ];
  return (
    <section className="min-h-screen px-9 bg-zinc-100 py-5">
      {isMobile ? (
        <h1 className="font-amatic text-5xl text-center mb-8">Products</h1>
      ) : (
        <h1 className="font-amatic text-8xl text-center mb-8">Products</h1>
      )}
      <section className="flex flex-wrap justify-around gap-6 relative">
        {productsList.map((product, i) => (
          <article
            key={i}
            className="w-96 h-[450px] bg-white border flex flex-col justify-center items-center p-5 space-y-2 rounded-lg border-gray-300"
          >
            <div className="image">
              <img
                className="w-[15rem] h-[260px] object-cover rounded-lg inline-block"
                src={product.img}
                alt={product.productName}
              />
            </div>
            <h2 className="productname text-xl font-bold">
              {product.productName}
            </h2>
            <div className="price text-green-700 flex justify-center items-center space-x-5 ">
              <span className=" w-0">
                {" "}
                <IndianRupee size={12} width={25} />
              </span>
              <p className="font-bold">{product.discount}</p>
              <span className="w-0">
                {" "}
                <IndianRupee size={12} width={25} />
              </span>
              <div className="relative text-black flex justify-center">
                <p className="border absolute bottom-3 w-7 border-green-600"></p>
                {product.price}
              </div>
            </div>
            <div className="button w-full text-center  hover:bg-green-500 transition-all duration-300 bg-green-600 text-white cursor-pointer rounded-lg py-3">
              <button className="text-lg">Add to cart</button>
            </div>
          </article>
        ))}
      </section>
    </section>
  );
};

export default AllProducts;


// // GENERATED BY CLAUDE.AI


// import { IndianRupee, ShoppingCart, Star, Filter, Search } from "lucide-react";
// import { useState } from "react";

// const AllProducts = ({ isMobile }) => {
//   const [searchTerm, setSearchTerm] = useState("");
//   const [sortBy, setSortBy] = useState("default");

//   const productsList = [
//     {
//       productName: "Maize Seeds",
//       price: "200",
//       discount: "142",
//       img: "/img/organicsoil.png",
//       category: "cereals",
//       rating: 4.5,
//       inStock: true,
//     },
//     {
//       productName: "Soybean Seeds",
//       img: "/img/humitek.png",
//       price: "340",
//       discount: "230",
//       category: "pulses",
//       rating: 4.7,
//       inStock: true,
//     },
//     {
//       productName: "Cotton Seeds",
//       img: "/img/vegitableseeds.png",
//       price: "400",
//       discount: "370",
//       category: "fiber",
//       rating: 4.3,
//       inStock: true,
//     },
//     {
//       productName: "Groundnut Seeds",
//       img: "/img/soilbooster.png",
//       price: "158",
//       discount: "110",
//       category: "oilseeds",
//       rating: 4.6,
//       inStock: false,
//     },
//     {
//       productName: "Wheat Seeds",
//       img: "/img/organicsoil.png",
//       price: "824",
//       discount: "567",
//       category: "cereals",
//       rating: 4.8,
//       inStock: true,
//     },
//     {
//       productName: "Rice Seeds",
//       img: "/img/humitek.png",
//       price: "550",
//       discount: "330",
//       category: "cereals",
//       rating: 4.9,
//       inStock: true,
//     },
//     {
//       productName: "Mustard Seeds",
//       img: "/img/vegitableseeds.png",
//       price: "80",
//       discount: "60",
//       category: "oilseeds",
//       rating: 4.4,
//       inStock: true,
//     },
//     {
//       productName: "Sunflower Seeds",
//       img: "/img/soilbooster.png",
//       price: "170",
//       discount: "150",
//       category: "oilseeds",
//       rating: 4.2,
//       inStock: true,
//     },
//   ];

//   // Calculate savings percentage
//   const calculateSavings = (price, discount) => {
//     return Math.round(((price - discount) / price) * 100);
//   };

//   // Filter and sort products
//   const filteredProducts = productsList
//     .filter((product) =>
//       product.productName.toLowerCase().includes(searchTerm.toLowerCase())
//     )
//     .sort((a, b) => {
//       if (sortBy === "price-low") return parseInt(a.discount) - parseInt(b.discount);
//       if (sortBy === "price-high") return parseInt(b.discount) - parseInt(a.discount);
//       if (sortBy === "rating") return b.rating - a.rating;
//       return 0;
//     });

//   return (
//     <section className="min-h-screen px-4 md:px-9 bg-gradient-to-b from-green-50 to-zinc-100 py-8">
//       {/* Header */}
//       <div className="max-w-7xl mx-auto">
//         {isMobile ? (
//           <h1 className="font-amatic text-5xl text-center mb-4 text-green-800">
//             Our Premium Seeds
//           </h1>
//         ) : (
//           <h1 className="font-amatic text-8xl text-center mb-4 text-green-800">
//             Our Premium Seeds
//           </h1>
//         )}
//         <p className="text-center text-gray-600 mb-8 max-w-2xl mx-auto">
//           Quality seeds for a bountiful harvest. Trusted by farmers across India.
//         </p>

//         {/* Search and Filter Bar */}
//         <div className="flex flex-col md:flex-row gap-4 mb-8 max-w-4xl mx-auto">
//           <div className="flex-1 relative">
//             <Search className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400" size={20} />
//             <input
//               type="text"
//               placeholder="Search seeds..."
//               value={searchTerm}
//               onChange={(e) => setSearchTerm(e.target.value)}
//               className="w-full pl-10 pr-4 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-green-500 focus:border-transparent outline-none"
//             />
//           </div>
//           <div className="relative">
//             <Filter className="absolute left-3 top-1/2 transform -translate-y-1/2 text-gray-400" size={20} />
//             <select
//               value={sortBy}
//               onChange={(e) => setSortBy(e.target.value)}
//               className="pl-10 pr-8 py-3 border border-gray-300 rounded-lg focus:ring-2 focus:ring-green-500 focus:border-transparent outline-none appearance-none bg-white cursor-pointer"
//             >
//               <option value="default">Sort By</option>
//               <option value="price-low">Price: Low to High</option>
//               <option value="price-high">Price: High to Low</option>
//               <option value="rating">Highest Rated</option>
//             </select>
//           </div>
//         </div>

//         {/* Products Grid */}
//         <section className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 xl:grid-cols-4 gap-6">
//           {filteredProducts.map((product, i) => {
//             const savings = calculateSavings(product.price, product.discount);
            
//             return (
//               <article
//                 key={i}
//                 className="bg-white border border-gray-200 rounded-xl overflow-hidden shadow-sm hover:shadow-xl transition-all duration-300 transform hover:-translate-y-2 flex flex-col group"
//               >
//                 {/* Image Container */}
//                 <div className="relative overflow-hidden bg-gray-100">
//                   {savings > 0 && (
//                     <div className="absolute top-3 left-3 bg-red-500 text-white px-3 py-1 rounded-full text-sm font-bold z-10 shadow-lg">
//                       {savings}% OFF
//                     </div>
//                   )}
//                   {!product.inStock && (
//                     <div className="absolute top-3 right-3 bg-gray-800 text-white px-3 py-1 rounded-full text-sm font-semibold z-10">
//                       Out of Stock
//                     </div>
//                   )}
//                   <img
//                     className="w-full h-64 object-cover group-hover:scale-110 transition-transform duration-500"
//                     src={product.img}
//                     alt={product.productName}
//                   />
//                 </div>

//                 {/* Content */}
//                 <div className="p-5 flex flex-col flex-grow">
//                   <h2 className="text-xl font-bold text-gray-800 mb-2">
//                     {product.productName}
//                   </h2>

//                   {/* Rating */}
//                   <div className="flex items-center gap-1 mb-3">
//                     {[...Array(5)].map((_, index) => (
//                       <Star
//                         key={index}
//                         size={16}
//                         className={
//                           index < Math.floor(product.rating)
//                             ? "fill-yellow-400 text-yellow-400"
//                             : "text-gray-300"
//                         }
//                       />
//                     ))}
//                     <span className="text-sm text-gray-600 ml-1">
//                       ({product.rating})
//                     </span>
//                   </div>

//                   {/* Price Section */}
//                   <div className="flex items-center gap-3 mb-4">
//                     <div className="flex items-center text-2xl font-bold text-green-700">
//                       <IndianRupee size={18} className="mr-1" />
//                       <span>{product.discount}</span>
//                     </div>
//                     {product.price !== product.discount && (
//                       <div className="flex items-center text-gray-400 line-through">
//                         <IndianRupee size={14} />
//                         <span className="text-sm">{product.price}</span>
//                       </div>
//                     )}
//                   </div>

//                   {/* Add to Cart Button */}
//                   <button
//                     disabled={!product.inStock}
//                     className={`w-full py-3 rounded-lg font-semibold text-white transition-all duration-300 flex items-center justify-center gap-2 mt-auto ${
//                       product.inStock
//                         ? "bg-green-600 hover:bg-green-700 active:scale-95 cursor-pointer"
//                         : "bg-gray-400 cursor-not-allowed"
//                     }`}
//                   >
//                     <ShoppingCart size={20} />
//                     {product.inStock ? "Add to Cart" : "Out of Stock"}
//                   </button>
//                 </div>
//               </article>
//             );
//           })}
//         </section>

//         {/* No Results */}
//         {filteredProducts.length === 0 && (
//           <div className="text-center py-16">
//             <p className="text-gray-500 text-lg">
//               No products found matching "{searchTerm}"
//             </p>
//           </div>
//         )}
//       </div>
//     </section>
//   );
// };

// export default AllProducts;